"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var base = "\n\n.e0.e1.e2.e3.e4,\n.e0.e1.e2.e3.e4:before,\n.e0.e1.e2.e3.e4:after,\n.e5.e6.e7.e8.e9,\n.e5.e6.e7.e8.e9:before,\n.e5.e6.e7.e8.e9:after {\n  box-sizing: border-box !important;\n}\n.e5.e6.e7.e8.e9 *,\n.e5.e6.e7.e8.e9 *:before,\n.e5.e6.e7.e8.e9 *:after {\n  box-sizing: inherit;\n}\n\n.e0.e1.e2.e3.e4,\n.e0.e1.e2.e3.e4:before,\n.e0.e1.e2.e3.e4:after,\n.e5.e6.e7.e8.e9,\n.e5.e6.e7.e8.e9:before,\n.e5.e6.e7.e8.e9:after,\n.e5.e6.e7.e8.e9 *,\n.e5.e6.e7.e8.e9 *:before,\n.e5.e6.e7.e8.e9 *:after {\n  margin: 0;\n  padding: 0;\n  border: 0;\n  width: auto;\n  height: auto;\n  vertical-align: baseline;\n  outline: none;\n  border-collapse: separate;\n  border-spacing: 0;\n}\n\n.e5.e6.e7.e8.e9,\n.e5.e6.e7.e8.e9:before,\n.e5.e6.e7.e8.e9:after,\n.e5.e6.e7.e8.e9 *,\n.e5.e6.e7.e8.e9 *:before,\n.e5.e6.e7.e8.e9 *:after {\n  font-family: Arial;\n  font-size: 16px;\n  font-style: normal;\n  font-weight: normal;\n  line-height: 1.5;\n  color: black;\n  text-decoration: none;\n  text-align: left;\n  letter-spacing: 0;\n}\n\n.e0.e1.e2.e3.e4.e10 {\n  box-sizing: content-box !important;\n}\n.e0.e1.e2.e3.e4.e10 > div > * {\n  width: auto !important;\n}\n\n";
var groups = {
    text: [
        'font',
        'color',
        'textAlign',
        'letterSpacing',
        'wordSpacing',
        'textShadow',
        'wordBreak',
        'textDecoration',
        'textTransform',
        'overflowWrap',
        'wordWrap',
        'whiteSpace',
        'userSelect',
        'MozUserSelect',
        'msUserSelect',
        'WebkitUserSelect',
        'textIndent',
        'textOverflow',
    ],
    box: [
        'background',
        'padding',
        'border',
        'borderRadius',
        'boxShadow',
        'boxSizing',
        'animation',
        'spacing',
        'layout',
    ],
    other: [
        'cursor',
        'overflow',
        'outline',
        'position',
        'top',
        'right',
        'bottom',
        'left',
        'width',
        'height',
        'minWidth',
        'maxWidth',
        'minHeight',
        'maxHeight',
        'float',
        'clear',
        'zIndex',
        'animation',
        'display',
        'visibility',
        'opacity',
        'margin',
        'verticalAlign',
        'userSelect',
        'MozUserSelect',
        'msUserSelect',
        'WebkitUserSelect',
    ],
};
exports.default = {
    base: base,
    groups: groups,
};
